"""User add roles

Revision ID: 4a839ec47a03
Revises: 6d2f534244a4
Create Date: 2026-05-03 07:50:18.408335

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4a839ec47a03"
down_revision: Union[str, Sequence[str], None] = "6d2f534244a4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    userrole_enum = sa.Enum(
        "buyer", "seller", "admin", name="userrole", create_type=True
    )
    userrole_enum.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("role", userrole_enum, server_default="buyer", nullable=False),
    )  # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "role")
    # ### end Alembic commands ###
