services:
 
  marketplace:
    build: .
    container_name: marketplace_app
    env_file: .env.prod
    ports:
      - "8000:8000"
    networks:
      - marketplace_network
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    command: bash -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 4"
  
  postgres:
      image: postgres:17
      container_name: marketplace_db
      env_file: 
        .env.prod
      ports:
        - "6432:5432"  
      volumes:
        - marketplace_data:/var/lib/postgresql/data
      networks:
        - marketplace_network
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} || exit 1"]
        interval: 10s
        timeout: 5s
        retries: 5
      restart: unless-stopped

  redis:
    image: redis:7
    container_name: marketplace_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - marketplace_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3  
    restart: unless-stopped
    command: redis-server --save 60 1 --loglevel warning    


  redis_gui:
    image: redis/redisinsight
    ports:
      - 5540:5540
    networks:
      - marketplace_network


  rabbitmq:
      image: rabbitmq:4.1.1-management-alpine
      container_name: marketplace_rabbit
      hostname: rabbitmq
      ports:
        - "5672:5672"
        - "15672:15672"
      volumes:
        - rabbitmq_data:/var/lib/rabbitmq
      networks:
        - marketplace_network 
      restart: unless-stopped
      env_file: .env.prod
      healthcheck:
        test: [ "CMD", "rabbitmq-diagnostics", "check_port_connectivity" ]
        interval: 10s
        timeout: 5s
        retries: 5


  marketplace_celery_service:
    build: .
    container_name: marketplace_celery
    env_file:
      - .env.prod
    networks:
      - marketplace_network
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped
    command: celery -A app.tasks.celery_app:celery_instance worker --loglevel=info
  

  marketplace_flower_service:
    build: .
    container_name: marketplace_flower
    env_file:
      - .env.prod
    ports:
      - "5555:5555"
    networks:
      - marketplace_network
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped
    command: celery --app=app.tasks.celery_app:celery_instance flower


  maildev:
    image: maildev/maildev
    environment:
      - TZ=Europe/Moscow
      - MAILDEV_WEB_PORT=1080
      - MAILDEV_SMTP_PORT=1025
    ports:
      - "1080:1080"
      - "1025:1025"
    logging:
      driver: 
        "json-file"
      options:
        max-size: "1m"
    networks:
      - marketplace_network

  prometheus:
    image: prom/prometheus:v2.54.1
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/rules.yml:/etc/prometheus/rules.yml
    ports:
      - "9090:9090"
    networks:
      - marketplace_network


  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    env_file:
      - .env.prod
    networks:
      - marketplace_network


volumes:
  marketplace_data:
  redis_data:
  rabbitmq_data:

networks:
  marketplace_network:
    driver: bridge      