services:
 
  
  postgres:
      image: postgres:17
      container_name: marketplace
      env_file: 
        .env.dev
      ports:
        - "6432:5432"  
      volumes:
        - marketplace_data:/var/lib/postgresql/data
      networks:
        - marketplace_network
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} || exit 1"]
        interval: 10s
        timeout: 5s
        retries: 5
      restart: unless-stopped

  redis:
    image: redis:7
    container_name: marketplace_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - marketplace_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3  
    restart: unless-stopped
    command: redis-server --save 60 1 --loglevel warning    


  redis_gui:
    image: redis/redisinsight
    ports:
      - 5540:5540
    networks:
      - marketplace_network


volumes:
  marketplace_data:
  redis_data:

networks:
  marketplace_network:
    driver: bridge      